version: "3"

services:
  # Setup express nodejs backend container
  server:
    build: ./my-app-backend
    expose:
      - ${APP_SERVER_PORT}
    environment:

      # Environment should be a list
      API_HOST: ${API_HOST}
      API_SERVER_PORT: ${APP_SERVER_PORT}
    volumes:
      - ./server/src:/my-app-backend/server
    command: npm run devStart
    tty: true

  # Setup react frontend container
  client:
    build: ./my-app-frontend
    depends_on:
      - server
    environment:
      REACT_APP_PORT: ${REACT_APP_PORT}
    expose:
      - ${REACT_APP_PORT}
    ports:
      - ${REACT_APP_PORT}:${REACT_APP_PORT}
    volumes:
      - ./client/src:/my-app-frontend/src
      - ./client/public:/my-app-frontend/public
    links:
      - server
    command: npm start
    tty: true