// User authentication
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_ERROR = 'REGISTER_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';

// Survey
export const CREATE_SURVEY_SUCCESS = 'CREATE_SURVEY_SUCCESS';
export const CREATE_SURVEY_ERROR = 'CREATE_SURVEY_ERROR';
export const QUESTIONS_SUCCESS = 'QUESTIONS_SUCCESS';
export const QUESTIONS_ERROR = 'QUESTIONS_ERROR';
export const DISPLAY_SURVEYS_SUCCESS = 'DISPLAY_SURVEYS_SUCCESS';
export const DISPLAY_SURVEYS_ERROR = 'DISPLAY_SURVEYS_ERROR';
export const DISPLAY_PREVIEW_SUCCESS = 'DISPLAY_PREVIEW_SUCCESS';
export const DISPLAY_PREVIEW_ERROR = 'DISPLAY_PREVIEW_ERROR';
export const OPEN_SURVEY_SUCCESS = 'OPEN_SURVEY_SUCCESS';
export const OPEN_SURVEY_ERROR = 'OPEN_SURVEY_ERROR';
export const CLOSE_SURVEY_SUCCESS = 'CLOSE_SURVEY_SUCCESS';
export const CLOSE_SURVEY_ERROR = 'CLOSE_SURVEY_ERROR';

// Questions
export const DELETE_QUESTION_SUCCESS = 'DELETE_QUESTION_SUCCESS';
export const DELETE_QUESTION_ERROR = 'DELETE_QUESTION_ERROR';