// User authentication
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_ERROR = 'REGISTER_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';

// Survey
export const DISPLAY_QUESTION_SUCCCESS = 'DISPLAY_QUESTION_SUCCESS';
export const DISPLAY_QUESTION_ERROR = 'DISPLAY_QUESTION_ERROR';